apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-grafana
spec:
  project: default
  destination:
    name: https://kubernetes.default.svc
    server: https://kubernetes.default.svc
    namespace: grafana
  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 7.3.11
      helm:
        releaseName: grafana
        valueFiles:
          - $values/argocd/apps/grafana_values.yaml
    - repoURL: https://github.com/Magier/Unguard-Attack-Defense-Demo.git
      targetRevision: HEAD
      ref: values
  syncPolicy: 
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
