cluster:
  name: unguard
externalServices:
  prometheus:
    host: https://prometheus-prod-24-prod-eu-west-2.grafana.net
    basicAuth:
      username: "1582271"
      password: glc_eyJvIjoiMTEyNTczMSIsIm4iOiJzdGFjay05MzMyOTItaW50ZWdyYXRpb24tZ3JhZmFuYS1zYS1ncmFmYW5hLXNhIiwiayI6ImpKNzV1M3IzSjBtN3VHc0MxUmEzcDJJNSIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
  loki:
    host: https://logs-prod-012.grafana.net
    basicAuth:
      username: "891073"
      password: glc_eyJvIjoiMTEyNTczMSIsIm4iOiJzdGFjay05MzMyOTItaW50ZWdyYXRpb24tZ3JhZmFuYS1zYS1ncmFmYW5hLXNhIiwiayI6ImpKNzV1M3IzSjBtN3VHc0MxUmEzcDJJNSIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
  tempo:
    host: https://tempo-prod-10-prod-eu-west-2.grafana.net:443
    basicAuth:
      username: "885389"
      password: glc_eyJvIjoiMTEyNTczMSIsIm4iOiJzdGFjay05MzMyOTItaW50ZWdyYXRpb24tZ3JhZmFuYS1zYS1ncmFmYW5hLXNhIiwiayI6ImpKNzV1M3IzSjBtN3VHc0MxUmEzcDJJNSIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
metrics:
  enabled: true
  cost:
    enabled: false
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: false
opencost:
  enabled: false
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
alloy: {}
alloy-events: {}
alloy-logs: {}