apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unguard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    # targetRevision: 12.2.4
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    app: unguard
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: unguard
  sources:
    - chart: unguard
      repoURL: https://github.com/magier/unguard-attack-defense-demo.git
      targetRevision: 0.9.2
      path: unguard
      helm:
        releaseName: unguard
    - chart: mariadb
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.0.6
      helm:
        releaseName: unguard-mariadb
        parameters:
          - name: "primary.persistence.enabled"
            value: "false"
    # - repoURL: https://github.com/Magier/Unguard-Attack-Defense-Demo.git
    #   targetRevision: HEAD
    #   ref: values
    # - repoURL: https://github.com/magier/unguard-attack-defense-demo.git
    #   targetRevision: HEAD
    #   path: unguard_netpol
      # helm:
        # releaseName: unguard
        # valueFiles:
        #   - $values/unguard/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      selfHeal: true
      # prune: true